"use client";
import "~/styles/globals.css";
import { Inter } from "next/font/google";
import Header from "./_components/header";
import { RecoilRoot } from "recoil";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Sidebar from "./_components/sidebar/sidebar";



const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

// export const metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

export default function RootLayout({
  children,
  params: { session, ...params },
}: {
  children: React.ReactNode;
  params: {
    session: any;
  };

}) {
  // const { data: session, status } = useSession()
  console.log(session, 'session');
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <main className="flex flex-row  h-screen items-center justify-center text-white pt-[80px] bg-background   ">

            <RecoilRoot>
              <Header />
         
              {children}
            </RecoilRoot>
          <ToastContainer />

        </main>
      </body>
    </html>
  );
}
