import "~/styles/globals.css";
import { Inter } from "next/font/google";
import Header from "./_components/header";
import { RecoilRoot } from "recoil";
import { ToastContainer, toast } from 'react-toastify';
import NextTopLoader from 'nextjs-toploader';

import 'react-toastify/dist/ReactToastify.css';



const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

// export const metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

export default function RootLayout({
  children,
  params: { session, ...params },
}: {
  children: React.ReactNode;
  params: {
    session: any;
  };

}) {
  // const { data: session, status } = useSession()
  console.log(session, 'session');
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <NextTopLoader color="#cc00ff" />
        <main className="  h-full min-h-screen text-white  bg-background pt-[80px]   ">

          {/* <RecoilRoot> */}


          <Header />

          {children}
          {/* </RecoilRoot> */}
          <ToastContainer />






        </main>
      </body>
    </html>
  );
}
