version: "3.8"
services:
  app:
      build: ./packages/backend
      ports:
        - "8080:8080"
      depends_on:
        - rabbitmq
        - database
      networks:
        - network-app
      volumes:
      - /home/anurag/s3mnt:/home/anurag/s3mnt
      
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network-app
    
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - network-app
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=streamvault
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  subtitler:
    build: ./packages/subtitler
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    networks:
      - network-app
    volumes:
    - /home/anurag/s3mnt:/home/anurag/s3mnt
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:rw
      - ./certbot/www/:/var/www/certbot/:rw
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
 

    

networks:
  network-app:
  


  
