name: backend
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
    
      - name: Add .env file
        run: touch ./packages/backend/.env && echo "${{ secrets.ENV_FILE }}" >> ./packages/backend/.env
    
      - name: remove previous containers
        run: docker compose down
      - name: Build the stack
        run: docker compose up -d --build
