name: backend
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Add backend.env file
        run: touch ./packages/backend/.env && echo "${{ secrets.ENV_FILE }}" >> ./packages/backend/.env
      - name: Add subtitler .env file
        run: touch ./packages/subtitler/.env && echo "${{ secrets.SUBTITLER_ENV_FILE }}" >> ./packages/subtitler/.env
      # - name: install backend deps
      #   run: cd packages/backend && go mod download
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          cd packages/subtitler && pip3 install -r requirements.txt
     
      

      - name: stop go backend
        run: sudo systemctl stop go-backend
      - name: stop subtitler
        run: sudo systemctl stop subtitler.service

      - name: Reload systemd
        run: sudo systemctl daemon-reload
     
      - name: start go backend
        run: sudo systemctl start go-backend

    
     
      - name: start subtitler
        run: sudo systemctl start subtitler.service

      - name: Reload systemd
        run: sudo systemctl daemon-reload

    
