name: backend
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install Docker
        run: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
      - name: Test docker
        run: docker --version
      - name: Build the stack
        run: docker compose up -d
