name: backend
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      
      - name: Add .env file
        run: touch ./packages/backend/.env && echo "${{ secrets.ENV_FILE }}" >> ./packages/backend/.env
      - name: stop go backend
        run: sudo systemctl stop go-backend
      - name: Reload systemd
        run: sudo systemctl daemon-reload
      - name: start go backend
        run: sudo systemctl start go-backend
      - name: Reload systemd
        run: sudo systemctl daemon-reload
    